apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Tamaño que solicitará el PVC
  storageClassName: manual  # Debe coincidir con la clase del PV
