apiVersion: v1
kind: Service
metadata:
  name: mi-api-service
spec:
  selector:
    app: mi-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007 # Puedes cambiar esto por cualquier puerto disponible entre 30000 y 32767
  type: NodePort

